**Anirudhda Pardhi** - s3807109 

## MATH2319 Machine Learning - Solution 1

## Part A

In [1]:
# Importing required modules
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np 
import math
import seaborn as sns

In [2]:
#importing the csv file
abc = pd.read_csv('THA_diamonds.csv', header=0)

In [3]:
#Copying orignal dataframe to another for reference
abc.head()

cut color  depth price  carat
0  Good     D   63.6   low   0.44
1  Fair     F   64.2   low   0.45
2  Good     I   60.4   low   0.50
3  Good     F   56.8   low   0.45
4  Fair     F   64.3   low   0.45

In [4]:
#Adding to be predict values in dataset in last row
df=abc.copy()
testdata = {'cut':['Good'],'color':['D'],'depth':[60],'price':['premium'],'carat':[0.71]}
testdataframe = pd.DataFrame(testdata)
df = pd.concat([df, testdataframe], axis=0)
df.tail(5)

cut color  depth    price  carat
208  Fair     D   57.5  premium   0.90
209  Fair     F   64.7  premium   0.90
210  Good     I   58.2  premium   0.93
211  Fair     F   58.9  premium   0.90
0    Good     D   60.0  premium   0.71

In [5]:
#checking the datatypes of attributes
df.dtypes

cut       object
color     object
depth    float64
price     object
carat    float64
dtype: object

In [6]:
#Statastical description of data
df.describe()

depth       carat
count  213.000000  213.000000
mean    62.199531    0.667277
std      2.829369    0.149859
min     55.300000    0.320000
25%     60.100000    0.510000
50%     63.400000    0.700000
75%     64.100000    0.720000
max     68.700000    1.010000

In [7]:
# checking null values
df.isnull().sum()

cut      0
color    0
depth    0
price    0
carat    0
dtype: int64

In [8]:
#checking for unique values present in cut
df['cut'].value_counts() 

Good    153
Fair     60
Name: cut, dtype: int64

In [9]:
#checking for unique values present in price
df['price'].value_counts()

low        93
medium     74
high       31
premium    15
Name: price, dtype: int64

In [10]:
#checking for unique values present in color
df['color'].value_counts()

F    92
I    63
D    58
Name: color, dtype: int64

In [11]:
# Defining feature and target dataset
target = df['carat']
Data = df.drop(columns=['carat'])

In [12]:
categorical_cols = Data.columns[Data.dtypes == np.object].tolist()
categorical_cols

['cut', 'color', 'price']

In [13]:
# checking catagorical values division
for categorical_col in categorical_cols:
    print(categorical_col + ':')
    print(Data[categorical_col].value_counts())
    print('\n')

cut:
Good    153
Fair     60
Name: cut, dtype: int64


color:
F    92
I    63
D    58
Name: color, dtype: int64


price:
low        93
medium     74
high       31
premium    15
Name: price, dtype: int64




## One-hot encoding of the categorical descriptive features

In [57]:
Data_encoded = Data.copy()  # retain original Data without encoding for further analysis

for col in categorical_cols:
    q = len(Data_encoded[col].unique())
    if (q == 2):
        Data_encoded[col] = pd.get_dummies(Data_encoded[col], drop_first=True)

Data_encoded = pd.get_dummies(Data_encoded)

In [15]:
print(f'Shape of Data_encoded is {Data_encoded.shape}\n')  

Data_encoded.sample(n=5, random_state=11)

Shape of Data_encoded is (213, 9)



cut  depth  color_D  color_F  color_I  price_high  price_low  \
143    0   65.8        0        0        1           0          0   
144    1   58.0        0        1        0           0          0   
69     1   63.7        1        0        0           0          1   
164    1   60.3        0        1        0           0          0   
177    1   62.4        0        0        1           1          0   

     price_medium  price_premium  
143             1              0  
144             1              0  
69              0              0  
164             1              0  
177             0              0

In [16]:
Data_encoded.describe(include='all').round(3)

cut    depth  color_D  color_F  color_I  price_high  price_low  \
count  213.000  213.000  213.000  213.000  213.000     213.000    213.000   
mean     0.718   62.200    0.272    0.432    0.296       0.146      0.437   
std      0.451    2.829    0.446    0.497    0.457       0.353      0.497   
min      0.000   55.300    0.000    0.000    0.000       0.000      0.000   
25%      0.000   60.100    0.000    0.000    0.000       0.000      0.000   
50%      1.000   63.400    0.000    0.000    0.000       0.000      0.000   
75%      1.000   64.100    1.000    1.000    1.000       0.000      1.000   
max      1.000   68.700    1.000    1.000    1.000       1.000      1.000   

       price_medium  price_premium  
count       213.000        213.000  
mean          0.347          0.070  
std           0.477          0.256  
min           0.000          0.000  
25%           0.000          0.000  
50%           0.000          0.000  
75%           1.000          0.000  
max           1.000          1.000

## Scaling of descriptive features

In [17]:
from sklearn import preprocessing
Data_scaler = preprocessing.MinMaxScaler()
Data_encoded_norm_numpy = Data_scaler.fit_transform(Data_encoded)

In [18]:
Data_encoded_norm_numpy

array([[1.        , 0.61940299, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.6641791 , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.38059701, 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.21641791, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.26865672, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.35074627, 1.        , ..., 0.        , 0.        ,
        1.        ]])

In [19]:
Data_encoded_norm_df = pd.DataFrame(Data_encoded_norm_numpy, 
                                    columns=Data_encoded.columns)

Data_encoded_norm_df.sample(n=4, random_state=11)

cut     depth  color_D  color_F  color_I  price_high  price_low  \
143  0.0  0.783582      0.0      0.0      1.0         0.0        0.0   
144  1.0  0.201493      0.0      1.0      0.0         0.0        0.0   
69   1.0  0.626866      1.0      0.0      0.0         0.0        1.0   
164  1.0  0.373134      0.0      1.0      0.0         0.0        0.0   

     price_medium  price_premium  
143           1.0            0.0  
144           1.0            0.0  
69            0.0            0.0  
164           1.0            0.0

In [20]:
print(f'Shape of Data_encoded_norm_df is {Data_encoded_norm_df.shape}\n') 

Data_encoded_norm_df.describe(include='all').round(3)

Shape of Data_encoded_norm_df is (213, 9)



cut    depth  color_D  color_F  color_I  price_high  price_low  \
count  213.000  213.000  213.000  213.000  213.000     213.000    213.000   
mean     0.718    0.515    0.272    0.432    0.296       0.146      0.437   
std      0.451    0.211    0.446    0.497    0.457       0.353      0.497   
min      0.000    0.000    0.000    0.000    0.000       0.000      0.000   
25%      0.000    0.358    0.000    0.000    0.000       0.000      0.000   
50%      1.000    0.604    0.000    0.000    0.000       0.000      0.000   
75%      1.000    0.657    1.000    1.000    1.000       0.000      1.000   
max      1.000    1.000    1.000    1.000    1.000       1.000      1.000   

       price_medium  price_premium  
count       213.000        213.000  
mean          0.347          0.070  
std           0.477          0.256  
min           0.000          0.000  
25%           0.000          0.000  
50%           0.000          0.000  
75%           1.000          0.000  
max           1.000          1.000

In [21]:
df_clean = Data_encoded_norm_df.assign(target = target.values)
df_clean.sample(n=4, random_state=11)

cut     depth  color_D  color_F  color_I  price_high  price_low  \
143  0.0  0.783582      0.0      0.0      1.0         0.0        0.0   
144  1.0  0.201493      0.0      1.0      0.0         0.0        0.0   
69   1.0  0.626866      1.0      0.0      0.0         0.0        1.0   
164  1.0  0.373134      0.0      1.0      0.0         0.0        0.0   

     price_medium  price_premium  target  
143           1.0            0.0    0.90  
144           1.0            0.0    0.72  
69            0.0            0.0    0.51  
164           1.0            0.0    0.77

In [22]:
df_clean.to_csv('df_diamond.csv', index=False)

In [23]:
xyz = pd.read_csv('df_diamond.csv', header=0)

## Display of last 10 rows after one-hot encoding and scaling

In [24]:
xyz.tail(10)

cut     depth  color_D  color_F  color_I  price_high  price_low  \
203  1.0  0.201493      0.0      0.0      1.0         0.0        0.0   
204  0.0  0.776119      0.0      1.0      0.0         0.0        0.0   
205  1.0  0.320896      0.0      0.0      1.0         0.0        0.0   
206  0.0  0.858209      0.0      1.0      0.0         0.0        0.0   
207  1.0  0.626866      0.0      1.0      0.0         0.0        0.0   
208  0.0  0.164179      1.0      0.0      0.0         0.0        0.0   
209  0.0  0.701493      0.0      1.0      0.0         0.0        0.0   
210  1.0  0.216418      0.0      0.0      1.0         0.0        0.0   
211  0.0  0.268657      0.0      1.0      0.0         0.0        0.0   
212  1.0  0.350746      1.0      0.0      0.0         0.0        0.0   

     price_medium  price_premium  target  
203           0.0            1.0    0.91  
204           0.0            1.0    0.90  
205           0.0            1.0    0.92  
206           0.0            1.0    0.91  
207           0.0            1.0    0.96  
208           0.0            1.0    0.90  
209           0.0            1.0    0.90  
210           0.0            1.0    0.93  
211           0.0            1.0    0.90  
212           0.0            1.0    0.71

### splitting train and test dataset after encoding

In [26]:
test_encoded_data = xyz.iloc[-1:]

In [27]:
test_encoded_data

cut     depth  color_D  color_F  color_I  price_high  price_low  \
212  1.0  0.350746      1.0      0.0      0.0         0.0        0.0   

     price_medium  price_premium  target  
212           0.0            1.0    0.71

In [28]:
train_encoded_data = xyz.loc[0:211, :]

In [29]:
train_encoded_data.tail(10)

cut     depth  color_D  color_F  color_I  price_high  price_low  \
202  1.0  0.134328      0.0      0.0      1.0         0.0        0.0   
203  1.0  0.201493      0.0      0.0      1.0         0.0        0.0   
204  0.0  0.776119      0.0      1.0      0.0         0.0        0.0   
205  1.0  0.320896      0.0      0.0      1.0         0.0        0.0   
206  0.0  0.858209      0.0      1.0      0.0         0.0        0.0   
207  1.0  0.626866      0.0      1.0      0.0         0.0        0.0   
208  0.0  0.164179      1.0      0.0      0.0         0.0        0.0   
209  0.0  0.701493      0.0      1.0      0.0         0.0        0.0   
210  1.0  0.216418      0.0      0.0      1.0         0.0        0.0   
211  0.0  0.268657      0.0      1.0      0.0         0.0        0.0   

     price_medium  price_premium  target  
202           0.0            1.0    1.01  
203           0.0            1.0    0.91  
204           0.0            1.0    0.90  
205           0.0            1.0    0.92  
206           0.0            1.0    0.91  
207           0.0            1.0    0.96  
208           0.0            1.0    0.90  
209           0.0            1.0    0.90  
210           0.0            1.0    0.93  
211           0.0            1.0    0.90

### Euclidean distance calculation using excel

In [33]:
# Shortest distance column represesnts 'Euclidean distance' and Associated_target column represent its associated carat value  
distance = pd.read_csv('df_diamo.csv', header=0)
distance.head(10)

cut     depth  color_D  color_F  color_I  price_high  price_low  \
0    1  0.619403        1        0        0           0          1   
1    0  0.664179        0        1        0           0          1   
2    1  0.380597        0        0        1           0          1   
3    1  0.111940        0        1        0           0          1   
4    0  0.671642        0        1        0           0          1   
5    0  0.783582        0        1        0           0          1   
6    1  0.626866        1        0        0           0          1   
7    1  0.626866        1        0        0           0          1   
8    1  0.589552        1        0        0           0          1   
9    0  0.716418        0        1        0           0          1   

   price_medium  price_premium  target  distance  shortestdistance  \
0             0              0    0.44  1.439506          0.007463   
1             0              0    0.45  2.257928          0.156716   
2             0              0    0.50  2.000223          1.017255   
3             0              0    0.45  2.014207          1.414233   
4             0              0    0.45  2.258976          1.414529   
5             0              0    0.45  2.277575          1.414922   
6             0              0    0.45  1.440917          1.415808   
7             0              0    0.45  1.440917          1.416594   
8             0              0    0.46  1.434234          1.419245   
9             0              0    0.50  2.265770          1.419893   

   Associated_target  
0               0.70  
1               0.90  
2               0.90  
3               0.51  
4               0.92  
5               0.44  
6               0.54  
7               0.62  
8               0.53  
9               0.57

## Part B

In [53]:
#For K = 1 nearest Eucliedian distance(shortest distance) is 0.007463 and its associated target value is 0.70
Kone = 0.70/1 
Kone

0.7

## Part C

In [49]:
##For K = 5 we calculate mean of first 5 nearest Eucliedian distance(shortest distance) and their associated target values.
Kfive=(0.70+0.90+0.90+0.51+0.92)/5
Kfive

0.7859999999999999

## Part D

In [38]:
###For K = 10 we calculate mean of first 10 nearest Eucliedian distance(shortest distance) and their associated target values.
Kten=(0.70+0.90+0.90+0.51+0.92+0.44+0.54+0.62+0.53+0.57)/10
Kten

0.663

## Part E

In [39]:
X_target = train_encoded_data['target']
X_Data = train_encoded_data.drop(columns=['target'])
X_test = test_encoded_data.drop(columns=['target'])

In [40]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsRegressor

#Create KNN Classifier for k=1
knn1 = KNeighborsRegressor(n_neighbors=1)

#Train the model using the training sets
knn1.fit(X_Data, X_target)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                    weights='uniform')

In [41]:
#Predict the response for test dataset k=1
y_pred1 = knn1.predict(X_test)
pred1= y_pred1.round(3)
pred1

array([0.7])

In [42]:
#Create KNN Classifier for k=5
knn5 = KNeighborsRegressor(n_neighbors=5)

#Train the model using the training sets
knn5.fit(X_Data, X_target)

#Predict the response for test dataset k=5
y_pred5 = knn5.predict(X_test)
pred5= y_pred5.round(3)
pred5

array([0.786])

In [43]:
#Create KNN Classifier for k=10
knn10 = KNeighborsRegressor(n_neighbors=10)

#Train the model using the training sets
knn10.fit(X_Data, X_target)

#Predict the response for test dataset k=10
y_pred10 = knn10.predict(X_test)
pred10 = y_pred10.round(3)
pred10

array([0.663])

### Gridsearch method to obtain best parameter values

In [44]:
from sklearn.model_selection import RepeatedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler

cv_method = RepeatedKFold(n_splits=5, 
                          n_repeats=3, 
                          random_state=999)

knn_regressor = KNeighborsRegressor()

params_knn_regressor = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10], 
                        'p': [2]}

gs_knn_regressor = GridSearchCV(estimator=knn_regressor, 
                  param_grid=params_knn_regressor, 
                  verbose=1, 
                  cv=cv_method)

gs_knn_regressor.fit(X_Data, X_target);

Fitting 15 folds for each of 10 candidates, totalling 150 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 150 out of 150 | elapsed:    0.9s finished


In [45]:
gs_knn_regressor.best_params_

{'n_neighbors': 4, 'p': 2}

## Part F

In [55]:
manualdata = {'method': ['1-KNN', '5-KNN', '10-KNN'],
        'prediction': [Kone, Kfive, Kten],
        'is_best': ['False', 'True', 'False']}
df_summary_manual = pd.DataFrame(manualdata)

### df_summary_manual table

In [56]:
df_summary_manual

method  prediction is_best
0   1-KNN       0.700   False
1   5-KNN       0.786    True
2  10-KNN       0.663   False